sudo: false
git:
  depth: 10
language: node_js
node_js:
  - '8'
  - '9'
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  # Remove examples directories, avoid install dependencies
  - rm -rf ./examples/
install:
  - yarn global add lerna
  - yarn global add codecov
  - yarn
script:
  - yarn run ci
after_script:
  - codecov
