sudo: false
git:
  depth: 10
language: node_js
node_js:
  - '8'
  - '10'
before_install:
  # Remove examples directories, avoid install dependencies
  - rm -rf ./examples/
install:
  - npm install
  - npm install -g codecov
script:
  # TODO: Use 'lerna run ci' instead
  - npm run ci
after_script:
  - codecov
