git:
  depth: 1
language: node_js
os: 
  - 'linux'
  - 'osx'
  -  'windows'
node_js:
  - '10'
  - '12'
  - '14'
install:
  - npm install
  - npm install -g codecov
script:
  - npm run ci
after_script:
  - codecov
